const texts = {
  debitCard: 'Debit Card',
  availableBalance: 'Available Balance',
  singaporeDollar: 'S$',
  hideCardNumber: 'Hide Card Number',
  showCardnumber: 'Show Card Number',
  topUpAccount: 'Top-up account',
  depositMoney: 'Deposit money to your account to use with card',
  weeklyLimit: 'Weekly spending limit',
  weeklyLimitIs: 'Your weekly spending limit is S$',
  havenSetLimit: 'You haven’t set any spending limit on card',
  freezeCard: 'Freeze card',
  cardActive: 'Your debit card is currently active',
  deactivatedCard: 'Deactivated cards',
  prevdeactivatedCards: 'Your previously deactivated cards',
  setWeeklyLimit: 'Set a weekly debit card spending limit',
  weeklyMeansText: 'Here weekly means the last 7 days - not the calendar week',
  save: 'Save',
};
export default texts;
