name: Build Action

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the stage-release branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  buildApp:
    runs-on: macOS-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Use node 10.X
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Dependency Install
        run: |
          echo "yarn install"
          yarn
          echo "Pod Install"
          cd ios && pod install
        shell: bash

      - name: Build Android
        run: |
          echo "Build Android"
          cd android && ./gradlew assembleRelease
        shell: bash

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-build
          path: aspireUI/android/app/build/outputs/apk/release/app-release.apk

      - name: Switch XCode Version to 12.5
        run: sudo xcode-select -s /Applications/Xcode_12.5.app

      - name: Archive ios
        run: |
          cd react-app/ios
          xcodebuild -workspace aspireUI.xcworkspace \
            -scheme aspireui \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/aspireUI.xcarchive \
            clean archive | xcpretty
    

      - name: Export app
        run: |
          cd react-app/ios && xcodebuild \
            -exportArchive \
            -archivePath $PWD/build/teachonline.xcarchive \
            -exportOptionsPlist $PWD/ExportOptions.plist \
            -exportPath $PWD/build
